-- Data type in sql
-- int,bigint -- whole number 1,100,200,400,9000
-- varchar, char, nvarchar - 
-- date - 
-- bit -
-- image - 
-- decimal, currency, money, numeric - 900.99 , 780.45
-- Types of query perform in SQL
-- DML(Data Manipulation Language) - Insert, Update, Delete
-- DDL (Data Definition Language) - Create, Alter, Drop
-- DCL (Data Control Language) - Grant, Revoke
-- TCL (Transaction Control Language) - rollback, commit, savepoint
-- SQL Query Command - Select
-- SQL Query Command - Select
-- Select * | <column_name> | <column_name> from <table_name>
-- Where <column_name> <operator> <operand value>
--